## Sensor Automations:

  - alias: 'Toilet On'
    trigger:
      - entity_id: binary_sensor.toilet
        platform: state
        to: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.toilet_on
        
  - alias: 'Toilet On'
    trigger:
      - entity_id: binary_sensor.toilet
        platform: state
        to: 'off'
    action:
      service: scene.turn_on
      entity_id: scene.toilet_off
        
## Set nighttime value for Health Graphs

  - alias: 'Set Nighttime input'
    trigger:
      platform: sun
      event: sunset
      offset: "-00:45:00"
    action:
      entity_id: input_number.nighttime
      service: input_number.set_value
      data:
        value: 20
        
  - alias: 'Set Daytime input'
    trigger:
      platform: sun
      event: sunrise
      offset: "-00:45:00"
    action:
      entity_id: input_number.nighttime
      service: input_number.set_value
      data:
        value: 0
        
## Set custom theme on startup
  - alias: 'System - Set Custom Theme at Startup'
    initial_state: 'true'
    trigger:
      platform: homeassistant
      event: start
    action:
      service: frontend.set_theme
      data:
        name: slate

## Browser-mod Switch views when something happens
  - alias: Change to Media Screen
    trigger:
      - platform: state
        entity_id: media_player.plex_projector
        to: 'playing'
      - platform: state
        entity_id: media_player.spotify
        to: 'playing'        
    action:
      service:  script.turn_on
      entity_id: script.navigate_to_media
        
#### Homekit make toggle a button:
#### This controls my IR blaster to send volume commands, so I can just keep tapping the button like it was an actual remote in Homekit.

  - alias: Sound Up
    trigger:
      - platform: state
        entity_id: switch.speakers_vol_up
        to: 'on'
    action:
      service:  switch.turn_off
      entity_id: switch.speakers_vol_up

  - alias: Sound Down
    trigger:
      - platform: state
        entity_id: switch.speakers_vol_down
        to: 'on'
    action:
      service: switch.turn_off
      entity_id: switch.speakers_vol_down

  - alias: Projector Off
    trigger:
      - platform: state
        entity_id: device_tracker.projector
        to: 'not_home'
    action:
      service: switch.turn_off
      entity_id: switch.speakers_input
 
 
  - alias: Projector On
    trigger:
      - platform: state
        entity_id: device_tracker.projector
        to: 'home'
    action:
      service: switch.turn_on
      entity_id: switch.speakers_input           


#### Sugar levels low ####  

  - alias: Low Blood Sugar!
    trigger:
      - platform: numeric_state
        entity_id: sensor.luke_cgm_sgv_mmol
        below: '4'
    action:
      - service: scene.create
        data:
          scene_id: snapshot_plant_table
          snapshot_entities:
            - light.plant_table
      - service: light.turn_on
        data:
            brightness: 150
            rgb_color: [255, 0, 0]
            entity_id:
              - light.plant_table    
      - service: browser_mod.popup
        data:
          title: Low Blood Sugar!
          card:
            type: 'custom:mini-graph-card'
            color_thresholds:
              - color: '#FF004C'
                value: 3
              - color: '#03B4FF'
                value: 5
              - color: '#03B4FF'
                value: 8                
              - color: '#B51BE4'
                value: 9
            line_width: 2
            points_per_hour: 6
            hours_to_show: 25
            height: 130
            update_interval: 30
            entities:
              - entity: sensor.buienradar_ground_temperature
              - entity: binary_sensor.night
                color: rgba(255,255,255,.25)
                y_axis: secondary
                smoothing: false 
                aggregate_func: min
                show_state: false
                show_line: false
                show_points: false
              - entity: input_number.range_high
                color: rgba(255,255,255,.1)
                smoothing: false 
                line_width: 1
                aggregate_func: max
                show_state: false
                show_line: true
                show_points: false
              - entity: input_number.range_low
                color: rgba(255,255,255,.1)
                smoothing: false 
                line_width: 1
                aggregate_func: max
                show_state: false
                show_line: true
                show_points: false
            state_map:
              - value: "off"
                label: "Day"
              - value: "on"
                label: "Night"
            icon: 'mdi:water-outline'
            align_state: right
            align_icon: right
            name_adaptive_color: true
            icon_adaptive_color: true
            show:
              icon: true
              legend: false
              name: false
              fill: false
              points: hover
          deviceID:
            - e3bcb892-264fae95
            - 0290dd82-2a03ce63
            - tablet
            
  - alias: Normal Blood Sugar
    trigger:
      - platform: numeric_state
        entity_id: sensor.luke_cgm_sgv_mmol
        above: '4'
    action:
      - service: scene.turn_on
        entity_id: scene.snapshot_plant_table
      - service: browser_mod.close_popup


      
#### Automate lights when watching movies, pause on toilet break ####  

  - alias: Plex Playing
    trigger:
      - platform: state
        entity_id: media_player.plex_projector
        to: 'playing'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      service:  script.turn_on
      entity_id: script.plex_moviestarted

  - alias: Plex Paused
    trigger:
      - platform: state
        entity_id: media_player.plex_projector
        to: 'paused'
    condition:
      - condition: state
        entity_id: light.toilet_1
        state: 'on'        
    action:
      - service: browser_mod.popup
        data:
          title: Movie Paused
          style:
            width: 400px
          card:
            type: 'custom:button-card'
            icon: mdi:play-circle
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.plex_continuemovie
            label: Continue Playing
            show_label: true
            size: 45%
            styles:
              card:
                - height: 400px
          deviceID:
            - e3bcb892-264fae95
            - 0290dd82-2a03ce63
            - tablet

      
  - alias: Plex Playing Break
    trigger:
      - platform: state
        entity_id: light.toilet_1
        to: 'on'
    condition:
      - condition: state
        entity_id: media_player.plex_projector
        state: 'playing'
    action:
      - service:  media_player.media_pause
        entity_id: media_player.plex_projector

      
  - alias: Plex Playing Break Study
    trigger:
      - platform: state
        entity_id: light.study
        to: 'on'        
    condition:
      - condition: state
        entity_id: media_player.plex_projector
        state: 'playing'
    action:
      service:  media_player.media_pause
      entity_id: media_player.plex_projector
      
      
  - alias: Plex Playing Continue
    trigger:
      - platform: state
        entity_id: light.toilet_1
        to: 'unavailable'
    condition:
      - condition: state
        entity_id: media_player.plex_projector
        state: 'paused'
      - condition: state
        entity_id: light.study
        state: 'off'          
    action:
      service:  media_player.media_play
      entity_id: media_player.plex_projector        

  - alias: Plex Playing Continue Study
    trigger:
      - platform: state
        entity_id: light.study
        to: 'off'
    condition:
      - condition: state
        entity_id: light.toilet_1
        state: 'off'       
      - condition: state
        entity_id: media_player.plex_projector
        state: 'paused'
    action:
      service:  media_player.media_play
      entity_id: media_player.plex_projector            
    


  - alias: Plex Stopped
    trigger:
      - platform: state
        entity_id: media_player.plex_projector
        to: '0'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      service: script.turn_on
      entity_id: script.slowly_turn_on_livingroom
      

####  Updating status of Room Cleaning input ####  
      
  - alias: Vacuum Returning
    trigger:
      - platform: state
        entity_id: sensor.vacuum_status
        to: 'Returning home'
    action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.room_cleaning
        value: "goinghome"
        
  - alias: Vacuum Idle
    trigger:
      - platform: state
        entity_id: sensor.vacuum_status
        to: 'Idle'
    action:
      service: input_text.set_value
      data_template:
        entity_id: input_text.room_cleaning
        value: "paused"   
        
  - alias: Vacuum Charging
    trigger:
      - platform: state
        entity_id: sensor.vacuum_status
        to: 'Charging'
    action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.room_cleaning
        value: "charging"
        
 
 
 
  - alias: ui_sound_on
    trigger:
    - platform: state
      entity_id:
        ['light.door', 'light.stairs_2', 'light.bed', 'light.bedroom_roof', 'light.toilet_2', 'light.toilet_1', 'light.plant_table', 
        'light.table', 'light.couch', 'light.kitchen_4', 'light.kitchen_3', 'light.kitchen_2', 'light.kitchen_1', 'light.roof_plants',
        'light.roof_garden', 'switch.speakers_vol_up', 'switch.speakers_vol_down', 'switch.power', 'switch.speakers_input',
        'light.balcony','light.study']
      from: 'off'
      to: 'on'
    action:
    - service: media_player.play_media
      data:
        entity_id: media_player.tablet
        media_content_id: /local/ui/sound/on.m4a
        media_content_type: music

  - alias: ui_sound_off
    trigger:
    - platform: state
      entity_id:
        ['light.door', 'light.stairs_2', 'light.bed', 'light.bedroom_roof', 'light.toilet_2', 'light.toilet_1', 'light.plant_table', 
        'light.table', 'light.couch', 'light.kitchen_4', 'light.kitchen_3', 'light.kitchen_2', 'light.kitchen_1', 'light.roof_plants',
        'light.roof_garden', 'switch.speakers_vol_up', 'switch.speakers_vol_down', 'switch.power', 'switch.speakers_input',
        'light.balcony','light.study']
      from: 'on'
      to: 'off'
    action:
    - service: media_player.play_media
      data:
        entity_id: media_player.tablet
        media_content_id: /local/ui/sound/off.m4a
        media_content_type: music

  - alias: ui_sound_popup
    trigger:
      platform: event
      event_type: call_service
      event_data: 
        domain: browser_mod
        service: popup
    action:
    - service: media_player.play_media
      data:
        entity_id: media_player.tablet
        media_content_id: /local/ui/sound/popup.m4a
        media_content_type: music
        
  - alias: ui_sound_view
    trigger:
      platform: state
      entity_id: sensor.tablet_view
    action:
    - service: media_player.play_media
      data:
        entity_id: media_player.tablet
        media_content_id: /local/ui/sound/popup.m4a
        media_content_type: music     
          
          